### ISSUE TITLE
A recursive bug

### ISSUE THREAD

**Issue by DustinFader** [dan-lovelace/word-replacer-max#1]
If the condition of the word to be replaced like "Me" is also within the word like "Meow" that replaces it then during any kind of loading it continually replaces itself making it longer and longer "Meowowowowowowowowow". 
Pressing a drop down over and over again on google search is an easy way to reproduce it.

The length of the loading may also effect this. 

Tested on firefox, librewolf and chrome.

**Comment by dan-lovelace** [comment]
Hey @DustinFader thanks for the report. This should be resolved as of version [0.0.2](https://github.com/dan-lovelace/word-replacer-max/releases/tag/v0.0.2). Depending on your browser settings, you may get the new version automatically after the store submissions are approved. Firefox is already hosting the new version, Chrome usually takes a couple days.

I'll close this one out for now but please don't hesitate to reopen if the latest version does not resolve your problem.
