### ISSUE TITLE
Double text

### ISSUE THREAD

**Issue by trappersak** [dan-lovelace/word-replacer-max#31]
Text after repalcements is partly doubled.

https://cdn.wordreplacermax.com/979b1c6a-0c0b-4d8e-870f-27c1b7b91a2b.json

![ff](https://github.com/user-attachments/assets/c21244c0-208f-4809-9414-eb76e5b7410c)

**Comment by dan-lovelace** [comment]
Hello @trappersak -

Thanks for reporting this issue. From what I can tell at first glance, this particular website does a bit more dynamic loading than expected. They're fetching their headline text again after the initial load. By the time the second update comes across, the replacements from the first have already taken place.

Please allow me some time to come up with a solution. I will keep you updated here.

## Notes

- Affected URL: https://www.bild.de/politik/inland/ampel-koalition-gebrochen-darum-kann-merz-den-kanzler-nicht-stuerzen-672ca9ae048fa103a43c30c3

**Comment by dan-lovelace** [comment]
@trappersak -

This issue should be resolved as of version 0.8.1. It's been submitted to both Chrome and Firefox, please allow up to two days for them to publish it. Once you have the new version, don't hesitate to reach back out if you're still experiencing problems.

Thank you for bringing this to my attention!

Here's a preview of the fix in action:

![Screenshot 2024-11-08 at 6 11 25 PM](https://github.com/user-attachments/assets/e305c6d4-c882-4192-b947-02b5d97f58c2)
